version: "3.9"

services:
  app:
    build: .
    ports:
      - "9000:9000"
    volumes:
      - ./src:/app/src
    depends_on:
      - mongo
      - redis

  # MongoDB
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # Redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
volumes:
  mongo-data: